#!/usr/bin/env bun
/**
 * Generate the promo TTS clips for the landing page + README using MiMo's own
 * TTS — the product dogfooding itself. Each script is POSTed to a running
 * Mio agent server's `/tts` endpoint and the audio is written into
 * docs/assets/.
 *
 * Prereqs:
 *   1. A MiMo provider connected (Settings -> Providers -> MiMo in the desktop
 *      app; `mimo serve` reuses that stored key).
 *   2. The agent server running on a fixed port, e.g. from the repo root:
 *        bun run dev:agent serve --port 4096
 *   3. (optional) ffmpeg on PATH — clips are converted wav -> mp3 to keep the
 *      repo lean. Without it the .wav is kept and the page falls back to it.
 *
 * Run from the repo root:
 *   bun run script/gen-promo-tts.ts
 *   MIO_SERVER=http://127.0.0.1:5000 bun run script/gen-promo-tts.ts   # custom port
 */

import { rm } from "node:fs/promises"
import path from "node:path"

const SERVER = (process.env["MIO_SERVER"] ?? "http://127.0.0.1:4096").replace(/\/+$/, "")
const ROOT = path.resolve(import.meta.dir, "..")
const ASSETS = path.join(ROOT, "docs", "assets")
// Any valid project dir resolves an instance; the repo root works.
const DIRECTORY = ROOT

// Optional Basic auth — only needed if the server was started with a password.
const USER = process.env["MIO_SERVER_USERNAME"]
const PASS = process.env["MIO_SERVER_PASSWORD"]

type Clip = { id: string; voice: string; text: string }

const CLIPS: Clip[] = [
  {
    id: "promo-en",
    voice: "Chloe",
    text:
      "The voice you're hearing right now was generated by Mio itself. " +
      "It's a free, open-source desktop coding agent for the MiMo models — it reasons over your " +
      "screenshots, PDFs and video, takes your prompts by voice, and reads its answers back. " +
      "Built for Windows and macOS.",
  },
  {
    id: "promo-zh",
    voice: "冰糖",
    text:
      "你现在听到的这段声音，就是 Mio 自己生成的。它是一款面向 MiMo 模型家族的原生桌面编程助手——" +
      "看得懂你的截图、PDF 和视频，能听你用语音说需求，也能把答案读给你听。免费、开源，支持 Windows 和 macOS。",
  },
]

function authHeader(): Record<string, string> {
  if (!PASS) return {}
  const token = Buffer.from(`${USER ?? ""}:${PASS}`).toString("base64")
  return { Authorization: `Basic ${token}` }
}

async function reachable(): Promise<boolean> {
  return fetch(SERVER, { method: "GET" })
    .then(() => true)
    .catch(() => false)
}

async function synthesize(clip: Clip): Promise<Uint8Array> {
  const url = `${SERVER}/tts?directory=${encodeURIComponent(DIRECTORY)}`
  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json", ...authHeader() },
    body: JSON.stringify({ text: clip.text, voice: clip.voice, format: "wav" }),
  })
  if (!res.ok) {
    const detail = await res.text().catch(() => "")
    throw new Error(`${clip.id}: HTTP ${res.status} ${detail.slice(0, 300)}`)
  }
  const json = (await res.json()) as { audio?: string }
  if (!json.audio) throw new Error(`${clip.id}: response carried no audio`)
  return Buffer.from(json.audio, "base64")
}

async function toMp3(wavPath: string, mp3Path: string): Promise<boolean> {
  if (!Bun.which("ffmpeg")) return false
  const proc = Bun.spawn(["ffmpeg", "-y", "-i", wavPath, "-codec:a", "libmp3lame", "-q:a", "4", mp3Path], {
    stdout: "ignore",
    stderr: "ignore",
  })
  return (await proc.exited) === 0
}

async function main() {
  if (!(await reachable())) {
    console.error(
      `✗ No Mio agent server at ${SERVER}\n` +
        `  Start one (it reuses your connected MiMo key) from the repo root:\n` +
        `    bun run dev:agent serve --port 4096\n` +
        `  then re-run — set MIO_SERVER=http://127.0.0.1:<port> if you chose another port.`,
    )
    process.exit(1)
  }

  for (const clip of CLIPS) {
    process.stdout.write(`• ${clip.id} (voice: ${clip.voice}) … `)
    const bytes = await synthesize(clip)
    const wavPath = path.join(ASSETS, `${clip.id}.wav`)
    await Bun.write(wavPath, bytes)

    const mp3Path = path.join(ASSETS, `${clip.id}.mp3`)
    const converted = await toMp3(wavPath, mp3Path)
    if (!converted) {
      // No ffmpeg: drop any stale mp3 so the page's wav fallback is actually
      // served. The mp3 <source> is listed first, so a leftover mp3 from an
      // earlier run would shadow the freshly written wav.
      await rm(mp3Path, { force: true })
      console.log(`✓ ${path.relative(ROOT, wavPath)} (no ffmpeg — kept wav)`)
      continue
    }
    // Prefer the much smaller mp3; the page lists wav only as a fallback source.
    await rm(wavPath, { force: true })
    const kb = Math.round(Bun.file(mp3Path).size / 1024)
    console.log(`✓ ${path.relative(ROOT, mp3Path)} (${kb} KB)`)
  }

  console.log("\nDone. Preview: open docs/index.html → the “See, hear, and speak.” section.")
}

main().catch((err) => {
  console.error(`✗ ${err instanceof Error ? err.message : String(err)}`)
  process.exit(1)
})
